# Custom Language File for Launcher Customizer

[ejs.app]
title = "PokeSwidou Launcher"

[ejs.landing]
mediaGitHubURL = "https://pokeswidou.websr.gg/"
mediaXURL = "https://x.com/le_Swid"
mediaInstagramURL = "https://www.instagram.com/le_swid?igsh=a3YzcDVjbHF4ajYx"
mediaYouTubeURL = "https://www.youtube.com/@MisterSwid"
mediaDiscordURL = "https://discord.gg/HgTxQ4xh2J"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://pokeswidou.websr.gg/support/tickets"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR POKESWIDOU"
welcomeDescription = "Rejoignez la communauté PokeSwidou ! Lancez-vous dans l'aventure, capturez des Pokémon, défiez les arènes et devenez le meilleur dresseur du serveur."
welcomeDescCTA = "Tu n'es plus qu'à un clic de commencer ton aventure."
